create database casestudy

 Select * from dbo.fact

 Select * from [dbo].[Location]

 Select * from [dbo].[Product]


 --1) Display number of states present in location table?

	 Select count(distinct State) as State from Location

 --2) How many products are of regular type ?

	 Select count(distinct product) from product where type ='Regular'

 --3) How much spending has been done on marketing of product id 1 

	  select sum(marketing) as Product1Marketing from fact where ProductId=1

 --4) What is the minimum sales of a product ?

	 Select MIN(Sales) MIN_Sales from fact

 --5) Display max Cost of Good Sold(COGS).

  select MAX(COGS)	 from fact

 --6) Display the Details of the productid where product type is coffee 

	Select * from product where product_type='coffee'

 --7) Display the details where total_expenses is greater than 40.

 Select * from fact where Total_Expenses>40

 --8) What is the average sales in Area_Code 719 ? 

	Select AVG(Sales)as AVG_Sales from fact  where Area_Code=719

 --9) Find out the total profit generated by Colorado state. 

 Select Sum(Profit) as Colorado_Profit
 from fact F
 inner join Location L
 on F.Area_Code=L.Area_code
 where State='Colorado'

 --10) Display the average inventory for each product id.

	Select ProductId,Avg(Inventory) Avg_inventory  from fact Group by ProductId
	order by ProductId

	--11) Display state in a sequential order in a location table.

	--Ascending order

	Select distinct State from location order by state

	--Descending order
	Select distinct state from location order by state desc

	--12) Display the average budget margin where average budget margin 
	--of the product id should be greater than 100

	select Productid,Avg(Budget_margin) Avg_budget_Margin from fact group by
	productid having avg(budget_margin)>100	order by productid

	--13) What is the total sales done on date 2010-01-01 

	 Select Sum(Sales) Total_Sales from fact where date='2010/01/01'

	--14) Display the average total expense of each product id on individual date 

	Select Date,ProductId,AVG(Total_Expenses) Total_expence from fact  group by ProductId,Date
	order by ProductId,Date

	--15) Display the table with the following attributes such as Date, 
	--productid, product_type, product, Sales, profit, state, area_code 

	  Select  Date,F.ProductId, product_type, product, Sales, profit,state, F.Area_Code 
	  from fact	F
	  inner join product P
	  on  F.ProductId=P.productid
	  inner join Location L
	  on  F.Area_Code=L.area_code

	--16) Display the rank without any gap to show the Sales wise rank.

	   Select Dense_RANK()over(order by sales desc)	Rank,Sales from fact

	--17) Find the State wise Profit and Sales.

	Select State,Sum(profit)total_profit,Sum(sales)Total_Sales
	from fact F
	inner join Location L
	on F.Area_Code=L.area_code
	group by State
	

	--18) Find the State wise Profit and Sales along with the Product Name.

	  Select Product,State,Sum(profit)total_profit,Sum(sales)Total_Sales
	from fact F
	inner join Location L
	on F.Area_Code=L.area_code
	inner join Product P
	on F.ProductId=P.productid
	group by State,Product

	
	--19) If there is an increase in sales of 5%. Calculate the increased sales.

	Select Sales,(Sales*0.05) fiveper,(Sales+(Sales*0.05)) increased_sales from fact

	Select Sales,(Sales*1.05)  increased_sales from fact

	
	100 + 5 = 105

	5%=5/100= 100*0.05	=5

	105% =105/100=1.05


	--20) Find the maximum profit along with the Product id and Product Type.

	Select F.Productid,product_type,max(profit)
	from fact F
	inner join Product P
	on F.ProductId=P.productid
	group by F.Productid,product_type


	Select F.Productid,product_type,profit
	from fact F
	inner join Product P
	on F.ProductId=P.productid
	where Profit=( Select max(Profit) from fact	)

	